### PR TITLE
Add support for Visual Studio 2015

### PR DESCRIPTION
**Pull request by ballance**

### CODE REVIEW

**Comment by devlead** [comment]
Think #19 and #20 already targets this not a @nancyfx maintainer so don't now whats holding those issues up.

Meanwhile you could use [SideWaffle](https://github.com/ligershark/side-waffle) extension to get Nancy project templates working with VS2015.

**Comment by khellang** [comment]
Yeah, now we have #18, #19, #20 and #21 that does the same thing :stuck_out_tongue_closed_eyes:

**Comment by devlead** [comment]
@khellang then there's perhaps a need that shouldn't be ignored? :wink:

I just sent a PR ( ligershark/side-waffle#316 ) to SideWaffle to get it from 0.22 to 1.4.1 perhaps the way to go and obsolete this unmaintained repo?

**Comment by khellang** [comment]
Yeah, I'll leave that up to @thecodejunkie and @grumpydev to decide. I think the reason this repo has been neglected is that it requires *loads* of manual work to get an updated package out.

**Comment by thecodejunkie** [comment]
This is on my conscious. Updating the templates to support VS2015 is the small part, it's actually generating the new template files that is the massive PITA. There are *a lot* of manual work require (as you know @devlead), which is the main reason I've not updated them in a long time. So not only do we need to bump it to VS2015, we also need to bump them to `1.4.1` (soon `1.4.2`).

To generate new versions you need to:

1. Load the solution
1. Update the nugets
1. Individually (manually!) run the `Export project template` wizard on *each* project and fill out a bunch of fields
1. Once 3 is done, you need to manually unzip them (locally) and edit the manifest files because the wizard won't let you set all the required metadata
1. Zip them back up again
1. Generate the vsix file
1. Upload

There are *hours* of work to do this and you need to be very careful so you don't mess something up or miss one of the templates.

I know you created a tool a while back to do this, and perhaps the best thing would be to either

* Revive that tool and actually use it :)
* Stop official support for project templates

It would be a shame to stop supporting them, but for the past 12 months (at least) I've had to prioritize other things (Nancy related) with the time I've had to spend on it.

We have talked to people at MS and pointed out how much this suck, but there's been no changes in 2 years so I'm not going to hold my breath for a change anytime soon. This is something that needs to support automation. period.

**Comment by devlead** [comment]
@thecodejunkie sorry wasn't meaning to sound so blunt, but I can also see the frustration of the "users" getting the silent treatment :wink:.
Think first question is there anything the SideWaffle solution doesn't solve? Is it good enough?
Personally i I'm sorta against the "templatepack" where I get allot of templates I might no be interested in. SideWaffle feels like treating a symptom, not finding a cure, created just because the official way is just such a PITA. Also it would mean the Nancy templates are in the hands of somebody else, which can be both good and bad.
So as a user I would prefer the Nancy Templates to live on.

I'm totally 100% agreeing that this needs to be automated and preferably in a way that's generic and reusable, basically data/configuration driven.

That was my goal when I created pr #12 2 years ago, haven't given it too much though since.
Regardless it would take hours of work to do too, but it would be a one time effort for 1st VSIX and future VSIXes would be seconds.
This could probably be something I could lift into an @cake-build add-in actually think some of the features in the #12 pr has made it into Cake.

@thecodejunkie I'm totally swamped currently if I were to take a stab at it:
1. Are the [Nancy/src/Nancy.Demo.*](https://github.com/NancyFx/Nancy/tree/master/src/) projects the most "up-to-date" sample code around?
2. Is VS2012 interesting at today or would 2013 & 2015 be sufficient?

**Comment by thecodejunkie** [comment]
@devlead oh I did not take your comment as being blunt, sorry if it came across like that. I do agree that the silent treatment is the worst treatment. I'm not happy with how I've handled that, it just became one of those "I need to look at this - at some point" things. I need to check the side waffle templates and see what they offer. 

At a quick glance it looks like they're based on the templates that we put in the VSIX, so they should be sufficient. I will install SideWaffle later and take them for a spin. To be honest, it offer such a nicer experience (for maintenance) then the VSIX approach, that it would be the preferred approach moving forward

1. Yes they are, we have them in the main solution so we continuously build them with the project. Some needs a bit of love and we can probably kill a couple of them as well (and might just do that for the v2 work)
1. Na, VS2013 would probably be the bare minimum that we supported today

**Comment by tofutim** [comment]
VS2015 is needed, or should re-write the docs which point to using the template in the very first project. https://github.com/NancyFx/Nancy/wiki/Introduction

**Comment by kjpluck** [comment]
I agree with @tofutim, I'm trying to convince new company to use nancy but tripping right on the very first hurdle.  Please update the docs to not use templates until the templates are available.

**Comment by grumpydev** [comment]
I think the wiki should be updated to remove the reference to these templates - unless we can find a maintainer, or a tool to allow easy maintenance, then keeping this up to date is a non-starter.

**Comment by khellang** [comment]
Let's move the discussion to #18. We don't need this spread across 4 PRs :smile:

**Comment by tofutim** [comment]
I don't mind not having templates. Just need instructions on how to make
the basic Nancy site from scratch.

**Comment by thecodejunkie** [comment]
@tofutim let's keep it in #18 thanks =)

**Comment by thecodejunkie** [comment]
Actually let's keep it in here and close everything else - this thread has the most interesting discussions of them all

**Comment by thecodejunkie** [comment]
@devlead What would it take to get the project back on track?

> 1. Are the Nancy/src/Nancy.Demo.* projects the most "up-to-date" sample code around?
Those in the main repo? Yes, they're always updated when we change code in Nancy. Why? These aren't the base for the templates

> 2. Is VS2012 interesting at today or would 2013 & 2015 be sufficient?
2013 + 2015 are the interesting versions

**Comment by thecodejunkie** [comment]
Moving the discussion over to #12 

@ballance To clarify why this was closed - neither of the open pull-requests are going to be pull in right now. See https://github.com/NancyFx/Nancy.Templates/pull/21#issuecomment-157003366 why this is

Just adding VS2015 support is not enough for us to maintain them, we need to find a way to automate the process so that the Nancy version can be kept up to date as well

Thanks for the PR, but this one falls on me =/

**Pull request closed without merging**
